### ISSUE TITLE
Release protocol and candidate on PyPI

### ISSUE THREAD

**Issue by sixpearls** [kb-press/ndsplines#46]
We need to figure out the release protocol (instructions for manual release or using CI to release using some specific trigger) and push up a candidate to PyPI. @ixjlyons would you mind taking point on this?

**Comment by ixjlyons** [comment]
I think there's some pretty sophisticated stuff that can be done with azure pipelines, like setting up a criterion where you manually intervene to let the pipeline proceed (would probably want that for auto-publishing a tagged build to PyPI). Maybe it's more like manually triggering a separate release pipeline -- haven't read up on it much yet.

Currently, #47 implements building a wheel and making it available for each OS/Python version. So to make a release, you'd do something like the following:

```
$ rm -rf dist/*
$ python setup.py build_ext --inplace
$ python setup.py sdist
-- download the wheel files from azure pipelines to dist/
$ twine upload dist/*
```

It might be easier to play around with automation more now than later, what do you think?

**Comment by sixpearls** [comment]
I'd say let's do what we'd be happy with never coming back to. In particular, I think if you want to play with it, you should definitely do it now. If you're not interested in figuring it out then I think it would be fine to leave it with the protocol you mentioned.

**Comment by ixjlyons** [comment]
Spent a good couple hours last night going back and forth with different options. The main problem (really an annoyance) is that the current setup forces compilation on Linux. This wouldn't be too bad (compiling the _bspl extension module takes ~5 seconds for me), but for some reason pip/PyPI decides to pull the numpy and scipy sdists instead of the wheels as I mentioned above. Those compile times are something like 10s of minutes if I remember correctly. Some options:

- Remove the numpy bootstrap (i.e. `setup_requires`) so compilation isn't the default. This seems alright but I don't really like the heavy dependence on whether or not I have such a common library installed. Dependence on pre-installed Cython is more understandable.
- Remove the logic in `setup.py` that creates the extension module if you have numpy pre-installed in addition to removing `setup_requires`. This will require pre-installed Cython to compile.
- Remove the C file from the sdist package (and `if use_numpy` condition and `setup_requires`). Windows and Mac users get the fast version through the wheel and still have the option of using `pip install --no-binary`. Linux users have to pre-install Cython to compile.

The differences are somewhat subtle, but they're there. I'm now leaning against depending so much on what you have pre-installed -- I was focusing on what happens in a clean environment and forgetting that it's probably more common to add to an existing environment.

One of my concerns about getting into setting up Docker to build manylinux wheels was it felt a little fragile at first glance. After reading through [PEP 571](https://www.python.org/dev/peps/pep-0571/) a little more closely, I'm seeing it as a fairly official method of producing Linux wheels. Some of the major projects appear to use [MacPython](https://github.com/MacPython) as their wheel-building infrastructure, and they're using the [quay.io manylinux images](https://quay.io/repository/pypa/manylinux2010_x86_64) (good enough for them, good enough for me). It would essentially involve a one-liner to pull and run the image and a script/command to build and repair the wheel. It's probably inefficient compared to a proper Docker setup with Azure Pipelines, but it will only run at release time. Could always try to play around with caching the image or something if it's ultra slow, but it'll be 100% automated so it doesn't really even matter if it takes an hour to get the Linux wheel up on PyPI.

I'll try to get the Docker setup working tonight so we have wheels for all platforms, which to me is the best option by far. I still think we should think about forcing compilation when installing from the sdist and which option above is best for doing that.

**Comment by sixpearls** [comment]
I think I've seen installation instructions before that included manually installing requirements. Whether or not it's commonly done, I don't think it's a big deal to have the user manually do install the requirements especially if it's just for Linux users.

If you like the Docker path forward, great. If it becomes a headache, I think it would be almost as good to simplify the setup.py (since OSX and Win users get the wheel) and to minimally complicate the installation instructions for Linux users.

**Comment by ixjlyons** [comment]
https://github.com/kb-press/ndsplines/wiki/Release-Instructions
