### ISSUE TITLE
[JOSS] License Formatting

### ISSUE THREAD

**Issue by amritagos** [kb-press/ndsplines#53]
Part of https://github.com/openjournals/joss-reviews/issues/1745. Could you make the LICENSE file contain just the BSD-3 clause text for this project? It would be better to mention the other license (SciPy) in the project `README.md`, under an External libraries heading or under a Licenses heading. This is essentially to ensure that the license is instantly visible to whoever visits the repo. 

![image](https://user-images.githubusercontent.com/32496815/65140145-8cab5b80-da2b-11e9-9178-d3967bdffb17.png)

**Comment by sixpearls** [comment]
Hi @amritagos, we have reviewed this request and the options available to have GitHub parse the license file. We believe that the best place for the SciPy copyright/license information is in a dedicated and obvious license file in the root directory. It turns out that even adding a supplemental license file would cause GitHub to use the "See License" button rather than parsing the primary LICENSE file and putting the name in the header.

However, we do agree that it would be convenient to make the license type easier to determine. To address this, we added the name of the license to the top of the LICENSE file. Do you agree that his makes it sufficiently easy to determine the license for anyone who would like to know?

**Comment by amritagos** [comment]
Sure, that'll do. Thanks for detailing your fix.
