### ISSUE TITLE
API docs/docstrings

### ISSUE THREAD

**Issue by sixpearls** [kb-press/ndsplines#6]
Make sure everything is fully and accurately documented

**Comment by sixpearls** [comment]
Thanks for starting with #14. Should one of us make an account on RTD?

**Comment by ixjlyons** [comment]
Sure, I'd say go ahead and do it since the repo is under your account. If you also want to create a branch for working on getting readthedocs going and enable that branch in the admin settings, I can work on it there to avoid cluttering up master. I'm not totally sure if all the Cython stuff will just work, so there may be a few iterations.

What kind of requirements file setup do you like? `requirements.txt`, `requirements-doc.txt`, `requirements-dev.txt`? Some people put them in their own subdirectory, or just have `requirements.txt` and `requirements-dev.txt`.

Also, do you actually want the profiling script(s) run like the benchmarks? If not, we can exclude those to avoid installing `line_profiler` (I had to install it from git if I remember correctly).

**Comment by sixpearls** [comment]
> Sure, I'd say go ahead and do it since the repo is under your account. If you also want to create a branch for working on getting readthedocs going and enable that branch in the admin settings, I can work on it there to avoid cluttering up master. I'm not totally sure if all the Cython stuff will just work, so there may be a few iterations.

I have the project pointing to the init-docs branch, but I can make a new one if re-using the one from the PR was a bad idea.

> What kind of requirements file setup do you like? requirements.txt, requirements-doc.txt, requirements-dev.txt? Some people put them in their own subdirectory, or just have requirements.txt and requirements-dev.txt.

I was assuming the first option (if -doc and -dev are different), but I am fine with whatever a/the best practice is. Once you set it up, I can point RTD at it.

> Also, do you actually want the profiling script(s) run like the benchmarks? If not, we can exclude those to avoid installing line_profiler (I had to install it from git if I remember correctly).

No, I thought I had removed all the dependencies on `line_profiler`/removed the "profile" example scripts. I think all the behavior we want to show is in the examples.

**Comment by ixjlyons** [comment]
> I have the project pointing to the init-docs branch, but I can make a new one if re-using the one from the PR was a bad idea.

No I'm pretty sure it's fine to keep a branch going and repeatedly base PRs off of it.

> I was assuming the first option (if -doc and -dev are different), but I am fine with whatever a/the best practice is. Once you set it up, I can point RTD at it.

Ok. I'm thinking the dev/docs requirements will be pretty minimal so `requirements.txt` and `requirements-dev.txt` seems fine to me.

> No, I thought I had removed all the dependencies on line_profiler/removed the "profile" example scripts. I think all the behavior we want to show is in the examples.

Ah, ok. I think I moved the `1d-profile.py` script to `benchmarks/` when I was getting the `1d-benchmark.py` script together.

**Comment by sixpearls** [comment]
To what extent has #17 addressed this?

**Comment by sixpearls** [comment]
#49 will address this
